In [3]:
import pandas as pd

In [6]:
df = pd.read_csv("student_scores.csv")

In [7]:
df

   StudyHours  Score
0           1     15
1           2     25
2           3     35
3           4     45
4           5     55
5           6     65
6           7     75
7           8     85
8           9     92
9          10     98

In [8]:
df.head()

   StudyHours  Score
0           1     15
1           2     25
2           3     35
3           4     45
4           5     55

In [9]:
df.tail()

   StudyHours  Score
5           6     65
6           7     75
7           8     85
8           9     92
9          10     98

In [10]:
df.shape

(10, 2)

In [11]:
df.columns

Index(['StudyHours', 'Score'], dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudyHours  10 non-null     int64
 1   Score       10 non-null     int64
dtypes: int64(2)
memory usage: 292.0 bytes

In [14]:
df.describe()

       StudyHours      Score
count    10.00000  10.000000
mean      5.50000  59.000000
std       3.02765  28.786571
min       1.00000  15.000000
25%       3.25000  37.500000
50%       5.50000  60.000000
75%       7.75000  82.500000
max      10.00000  98.000000