In [1]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Bob'],
    'Age': [20, 21, np.nan, 22, 21],
    'Score': [85, 90, 78, np.nan, 90]
}

df = pd.DataFrame(data)

df

      Name   Age  Score
0    Alice  20.0   85.0
1      Bob  21.0   90.0
2  Charlie   NaN   78.0
3    David  22.0    NaN
4      Bob  21.0   90.0

In [2]:
df.isnull()

    Name    Age  Score
0  False  False  False
1  False  False  False
2  False   True  False
3  False  False   True
4  False  False  False

In [3]:
df.isnull().sum()

Name     0
Age      1
Score    1
dtype: int64

In [4]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

df['Score'] = df['Score'].fillna(df['Score'].mean())

df

      Name   Age  Score
0    Alice  20.0  85.00
1      Bob  21.0  90.00
2  Charlie  21.0  78.00
3    David  22.0  85.75
4      Bob  21.0  90.00

In [5]:
df.duplicated()

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      float64
 2   Score   5 non-null      float64
dtypes: float64(2), object(1)
memory usage: 252.0+ bytes

In [7]:
df.describe()

             Age      Score
count   5.000000   5.000000
mean   21.000000  85.750000
std     0.707107   4.918079
min    20.000000  78.000000
25%    21.000000  85.000000
50%    21.000000  85.750000
75%    21.000000  90.000000
max    22.000000  90.000000

In [8]:
print(df)

      Name   Age  Score
0    Alice  20.0  85.00
1      Bob  21.0  90.00
2  Charlie  21.0  78.00
3    David  22.0  85.75
4      Bob  21.0  90.00